name: medigo
description: "medigo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator:
  provider:
#  camera: ^0.9.8+1
#  permission_handler: ^10.4.5
#  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - "assets/"
